### ISSUE TITLE
KeyError: 'newCourse'

### ISSUE THREAD

**Issue by huadanfan** [startkkkkkk/Beijing_Daxuexi_Simple#17]
想问一下大佬这个问题应该怎么解决？
Traceback (most recent call last):
账号数量：1
  File "main.py", line 49, in <module>
--User 1--
    raise Exception(f'有{failed}个失败！')
登录成功
Exception: 有1个失败！
{'message': '请登录', 'code': 0}
Traceback (most recent call last):
  File "/home/runner/work/Beijing_Daxuexi_Simple/Beijing_Daxuexi_Simple/study.py", line 43, in study
    url = r['newCourse']['url']
KeyError: 'newCourse'

**Comment by startkkkkkk** [comment]
估计是登录请求因为网络问题失败了，应该是低概率事件
