### ISSUE TITLE
#24 修复之后任然报错

### ISSUE THREAD

**Issue by jingfengsama** [startkkkkkk/Beijing_Daxuexi_Simple#26]
#24 为两小时前关闭的ISSUE，但是新运行的ACTION仍然报错。

6小时前，约10月10日8点自动运行失败，刚刚手动运行也失败
注意到Fork中的Code中最近更新在3小时以前（约12点）
- --User 1--
登录成功
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    if study(username, password, ua):
  File "/home/runner/work/Beijing_Daxuexi_Simple/Beijing_Daxuexi_Simple/study.py", line 95, in study
    haveLearned = json.loads(r.text)
  File "/opt/hostedtoolcache/Python/3.7.[14](https://github.com/jingfengsama/Beijing_Daxuexi_Simple/actions/runs/3217359332/jobs/5260235971#step:9:15)/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)
Error: Process completed with exit code 1.

**Comment by jingfengsama** [comment]
同一天晚上6点又能用了
![OQQ{}W)8B0 @RQFTM I F2U](https://user-images.githubusercontent.com/78785393/194846596-2036c17c-b6d2-4b17-af41-44ee8bd42fa6.png)

**Comment by startkkkkkk** [comment]
有个地方没改到，已修复
