### ISSUE TITLE
> 请问补上速通链接已点过的期数的具体方法

### ISSUE THREAD

**Issue by z-rrr** [startkkkkkk/Beijing_Daxuexi_Simple#36]
> 我这里还是不行
> 
> > 刚刚试了，显示Error: raise Exception('貌似自己这显示完成了，但实际上没有？建议自己检查下(尤其是有团支书账号可以看到情况的)，然后可以在issue#31里反馈下') 团支书后台没有记录
> 
> 我这里刚刚试过，还是没有显示，我在想是不是因为之前我点过那个速通链接，多点了很多导致留下了不少空白的完成记录。但现在速通链接已经寄了，所以即使后台看不到完成记录，但在这里还是检测为已完成，所以就没有速通？是不是要等到空白记录都填上，这个程序才能发挥作用？

新的期数应该可以，以前的应该是这个情况，如果不想手动解决可以把文件主体那块换成一个循环补下以前的

_Originally posted by @startkkkkkk in https://github.com/startkkkkkk/Beijing_Daxuexi_Simple/issues/31#issuecomment-1286636353_
      
     小白请问您在这里说的“补下以前的”具体怎么操作呢，我试图直接修改study.py, 不再检查是否已经做过（直接注释Line80-82 QWQ我只是试试，不知道怎么改），然后就出现以下报错信息
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/urllib3/connection.py", line [175](https://github.com/z-rrr/qingniandaxuexi/actions/runs/3306226763/jobs/5456961831#step:5:176), in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

**Comment by SakuraLaurel** [comment]
要不试试每周用浏览器控制台吧。登录https://m.bjyouth.net/site/login，在控制台输入
```js
fetch('https://m.bjyouth.net/dxx/check', {'method':'POST','headers':{'Content-Type':'application/json'},'body':JSON.stringify({id:"93",org_id:4028763})})
```
其中最后一个字典里的id是本期期数93，下周94，以此类推

**Comment by z-rrr** [comment]
谢谢同学的分享，不过我今天发现他们更新之后之前速通链接留下的空白学习记录被删除了hhh，这个action可以正常运行了
