### ISSUE TITLE
可能是封了外网ip

### ISSUE THREAD

**Issue by ckqqqq** [startkkkkkk/Beijing_Daxuexi_Simple#38]
账号数量：1
--User 1--
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/urllib3/util/connection.py", line [9](https://github.com/ckqqqq/Beijing_Daxuexi_Simple/actions/runs/3383566266/jobs/5619584185#step:9:10)5, in create_connection
    raise err
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 1[10](https://github.com/ckqqqq/Beijing_Daxuexi_Simple/actions/runs/3383566266/jobs/5619584185#step:9:11)] Connection timed out

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='m.bjyouth.net', port=443): Max retries exceeded with url: /site/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa144955d90>: Failed to establish a new connection: [Errno 110] Connection timed out'))
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='m.bjyouth.net', port=443): Max retries exceeded with url: /site/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa1446cf090>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by lj976264709** [comment]
我也遇到了这个问题.....是封了Github的IP嘛

**Comment by skycosmos** [comment]
11月3日凌晨还是正常的，11月3日中午就出现上述情况。感觉是封了GitHub的IP。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Beijing_Daxuexi/Beijing_Daxuexi/study.py", line 20, in study
    touch = bjySession.get(url="https://m.bjyouth.net/site/login")
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='m.bjyouth.net', port=443): Max retries exceeded with url: /site/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8d01119790>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Error: The operation was canceled.

**Comment by skycosmos** [comment]
不知道可否利用本地运行的办法来解决。

**Comment by Gu0E** [comment]
亲测本地运行可以，直接在main.py里把username和password写上去就行









> 不知道可否利用本地运行的办法来解决。

**Comment by ckqqqq** [comment]
修改username和password
建立一个bat文件
`@echo off
d:
cd %~dp0
::在bat中执行cmd
cmd /k "cd /d D:\Code\Python\daxuexi\Beijing_Daxuexi_Simple&&D:\TOOL\Anaconda\Anaconda_root\python.exe D:\Code\Python\daxuexi\Beijing_Daxuexi_Simple\main.py"
exit`
建立一个计时器每2天运行一次bat就行
![图片](https://user-images.githubusercontent.com/62733988/199925470-c4039658-a786-49c3-b589-be49120b97d0.png)

**Comment by ckqqqq** [comment]
![图片](https://user-images.githubusercontent.com/62733988/199925699-d9129c6d-8ffb-47d0-b172-7ccbf54817b9.png)

**Comment by Gu0E** [comment]
> ![图片](https://user-images.githubusercontent.com/62733988/199925699-d9129c6d-8ffb-47d0-b172-7ccbf54817b9.png)

我在本地运行的时候出现了类似主楼的报错，请问一下是哪里出了问题呢？

这是我的bat文件
@echo off
d: 
cd %~dp0
 ::在bat中执行cmd
cmd /k "cd /d "D:\GitHub\Beijing_Daxuexi_Simple" && "D:\Program Files\Python310\python.exe" D:\GitHub\Beijing_Daxuexi_Simple\main.py"
exit
 
这是报错内容

Traceback (most recent call last):
  File "D:\GitHub\Beijing_Daxuexi_Simple\main.py", line 4, in <module>
    from study import study
  File "D:\GitHub\Beijing_Daxuexi_Simple\study.py", line 8, in <module>
    from utility import encrypt, cap_recognize
  File "D:\GitHub\Beijing_Daxuexi_Simple\utility.py", line 4, in <module>
    from Crypto.Cipher import PKCS1_v1_5 as Cipher_pksc1_v1_5
ModuleNotFoundError: No module named 'Crypto'

**Comment by MegaOwIer** [comment]
> > ![图片](https://user-images.githubusercontent.com/62733988/199925699-d9129c6d-8ffb-47d0-b172-7ccbf54817b9.png)
> 
> 我在本地运行的时候出现了类似主楼的报错，请问一下是哪里出了问题呢？
> 
> 这是我的bat文件 @echo off d: cd %~dp0 ::在bat中执行cmd cmd /k "cd /d "D:\GitHub\Beijing_Daxuexi_Simple" && "D:\Program Files\Python310\python.exe" D:\GitHub\Beijing_Daxuexi_Simple\main.py" exit
> 
> 这是报错内容
> 
> Traceback (most recent call last): File "D:\GitHub\Beijing_Daxuexi_Simple\main.py", line 4, in from study import study File "D:\GitHub\Beijing_Daxuexi_Simple\study.py", line 8, in from utility import encrypt, cap_recognize File "D:\GitHub\Beijing_Daxuexi_Simple\utility.py", line 4, in from Crypto.Cipher import PKCS1_v1_5 as Cipher_pksc1_v1_5 ModuleNotFoundError: No module named 'Crypto'

如果你确定所有依赖的模块都已经安装了可以检查一下安装好的 `Crypto` 模块的文件夹名称是不是 `crypto`，是的话把首字母改成大写就行。

**Comment by hauzax** [comment]
同本地报错，求问
Traceback (most recent call last):
  File "/Users/qiaohaoran/Beijing_Daxuexi_Simple/main.py", line 4, in <module>
    from study import study
  File "/Users/qiaohaoran/Beijing_Daxuexi_Simple/study.py", line 8, in <module>
    from utility import encrypt, cap_recognize
  File "/Users/qiaohaoran/Beijing_Daxuexi_Simple/utility.py", line 4, in <module>
    from Crypto.Cipher import PKCS1_v1_5 as Cipher_pksc1_v1_5
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 73, in <module>
    from Crypto.Util.number import ceil_div
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Crypto/Util/number.py", line 139
    value |= 2L ** (N-1)                # Ensure high bit is set
             ^
SyntaxError: invalid decimal literal

**Comment by ckqqqq** [comment]
安装依赖命令 pip install -r requirements.txt

**Comment by MegaOwIer** [comment]
> > > > ![图片](https://user-images.githubusercontent.com/62733988/199925699-d9129c6d-8ffb-47d0-b172-7ccbf54817b9.png)
> > > 
> > > 
> > > 我在本地运行的时候出现了类似主楼的报错，请问一下是哪里出了问题呢？
> > > 这是我的bat文件 @echo off d: cd %~dp0 ::在bat中执行cmd cmd /k "cd /d "D:\GitHub\Beijing_Daxuexi_Simple" && "D:\Program Files\Python310\python.exe" D:\GitHub\Beijing_Daxuexi_Simple\main.py" exit
> > > 这是报错内容
> > > Traceback (most recent call last): File "D:\GitHub\Beijing_Daxuexi_Simple\main.py", line 4, in from study import study File "D:\GitHub\Beijing_Daxuexi_Simple\study.py", line 8, in from utility import encrypt, cap_recognize File "D:\GitHub\Beijing_Daxuexi_Simple\utility.py", line 4, in from Crypto.Cipher import PKCS1_v1_5 as Cipher_pksc1_v1_5 ModuleNotFoundError: No module named 'Crypto'
> > 
> > 
> > 如果你确定所有依赖的模块都已经安装了可以检查一下安装好的 `Crypto` 模块的文件夹名称是不是 `crypto`，是的话把首字母改成大写就行。
> > 当然直接用 `pipenv` 之类的东西新建一个虚拟环境应该不会遇到这种问题。
> 
> 笑死我了，因为不知道依赖模块安装在哪，我把utility里的大写改成小写之后，pycharm里重新运行，就变成和上面一样的报错了（本来pycharm还可以跑）

改 `utility` 显然不行，因为库代码里面写的也是 `Crypto`。

**Comment by Gu0E** [comment]
> > > > > ![图片](https://user-images.githubusercontent.com/62733988/199925699-d9129c6d-8ffb-47d0-b172-7ccbf54817b9.png)
> > > > 
> > > > 
> > > > 我在本地运行的时候出现了类似主楼的报错，请问一下是哪里出了问题呢？
> > > > 这是我的bat文件 @echo off d: cd %~dp0 ::在bat中执行cmd cmd /k "cd /d "D:\GitHub\Beijing_Daxuexi_Simple" && "D:\Program Files\Python310\python.exe" D:\GitHub\Beijing_Daxuexi_Simple\main.py" exit
> > > > 这是报错内容
> > > > Traceback (most recent call last): File "D:\GitHub\Beijing_Daxuexi_Simple\main.py", line 4, in from study import study File "D:\GitHub\Beijing_Daxuexi_Simple\study.py", line 8, in from utility import encrypt, cap_recognize File "D:\GitHub\Beijing_Daxuexi_Simple\utility.py", line 4, in from Crypto.Cipher import PKCS1_v1_5 as Cipher_pksc1_v1_5 ModuleNotFoundError: No module named 'Crypto'
> > > 
> > > 
> > > 如果你确定所有依赖的模块都已经安装了可以检查一下安装好的 `Crypto` 模块的文件夹名称是不是 `crypto`，是的话把首字母改成大写就行。
> > > 当然直接用 `pipenv` 之类的东西新建一个虚拟环境应该不会遇到这种问题。
> > 
> > 
> > 笑死我了，因为不知道依赖模块安装在哪，我把utility里的大写改成小写之后，pycharm里重新运行，就变成和上面一样的报错了（本来pycharm还可以跑）
> 
> 改 `utility` 显然不行，因为库代码里面写的也是 `Crypto`。

已经死心了，每周打开pycharm手动跑一次8，总比老老实实看要省心，已经方便多了，感谢大佬

**Comment by AtlandisLee** [comment]
我在本地运行的时候无法安装onnx包应该怎么办呢，求助大佬
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime

**Comment by ckqqqq** [comment]
关闭所有vpn，cd 到项目根目录下运行
pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by ckqqqq** [comment]
> 我在本地运行的时候无法安装onnx包应该怎么办呢，求助大佬 ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none) ERROR: No matching distribution found for onnxruntime

如果还不行就编辑requirements.txt 然后把所有版本信息删掉

**Comment by AtlandisLee** [comment]
> 
vpn关掉了，还是不行orz
requirements里面我好像没看到有版本信息
我的python是3.11，这会有问题吗？

**Comment by ckqqqq** [comment]
> 

我的版本信息
sys：win 11
virtural env：anaconda
pip：21.2.4
python：3.9
![image](https://user-images.githubusercontent.com/62733988/201273516-56164554-ecfa-4c05-b2e3-df2bc6c629d8.png)
1 py11确实好新。
2 windows的任务计划程序需要用管理员模式跑bat。
3 如果import本地包有问题，多半是路径问题，可能需要手动设置根目录。

**Comment by AtlandisLee** [comment]
<img width="716" alt="1668147938185" src="https://user-images.githubusercontent.com/52619471/201277219-629aac40-c40c-4983-beb5-3ab830d7c337.png">
我现在只期望能手动跑通就足够了；
我现在还是卡在pip这一步上

**Comment by ckqqqq** [comment]
> <img alt="1668147938185" width="716" src="https://user-images.githubusercontent.com/52619471/201277219-629aac40-c40c-4983-beb5-3ab830d7c337.png">
> 
> 我现在只期望能手动跑通就足够了； 我现在还是卡在pip这一步上

https://pypi.org/project/onnxruntime/
https://blog.csdn.net/kun78684504/article/details/124983444

**Comment by AtlandisLee** [comment]
> > <img alt="1668147938185" width="716" src="https://user-images.githubusercontent.com/52619471/201277219-629aac40-c40c-4983-beb5-3ab830d7c337.png">
> > 我现在只期望能手动跑通就足够了； 我现在还是卡在pip这一步上
> 
> https://pypi.org/project/onnxruntime/ https://blog.csdn.net/kun78684504/article/details/124983444

我尝试了手动安装，最后发现问题还是出在python版本上，python3.11不支持onnx的任何一个wheel版本，我下载了python3.9后直接pip就成功了，非常感谢Orz
然后，在之前github action还可以工作的时候我就发现了一个问题，并且这个问题在本地运行也出现了，对于较长的USERNAME序列，总会在第8个用户附近失败
<img width="728" alt="image" src="https://user-images.githubusercontent.com/52619471/201310817-95621e54-6c1f-4341-ad81-f3dfe6e64278.png">
<img width="794" alt="image" src="https://user-images.githubusercontent.com/52619471/201311147-67a0efe0-16e9-4ff1-9def-5d7d57572aa3.png">

**Comment by surreyskahn** [comment]
请问大家多账号怎么填写USERMANE 和 PASSWORD

**Comment by xiaotianxt** [comment]
今天跑成功了一次

**Comment by startkkkkkk** [comment]
Github Actions的没有效果啦

> 今天跑成功了一次

**Comment by TogetherRolle** [comment]
> 请问大家多账号怎么填写USERMANE 和 PASSWORD

![image](https://user-images.githubusercontent.com/11836431/201579842-82993159-4438-4795-b195-175fe1815ac6.png)

**Comment by ckqqqq** [comment]
> 

在循环里面写个wait试试

**Comment by xiaotianxt** [comment]
> Github Actions的没有效果啦
> 
> 
> 
> > 今天跑成功了一次
> 
> 
> 
> 

😭

**Comment by DBeidachazi** [comment]
请问一下username和password填的是微信的吗

**Comment by ckqqqq** [comment]
![image](https://user-images.githubusercontent.com/62733988/205528917-8c55c6b1-17a7-4d2e-9017-c9c0b38ab4d4.png)
https://github.com/startkkkkkk/Beijing_Daxuexi_Simple
