### ISSUE TITLE
1月3日本地运行出现异常，登录后返回以下代码，请大佬们帮忙看看是什么问题，感谢！

### ISSUE THREAD

**Issue by surreyskahn** [startkkkkkk/Beijing_Daxuexi_Simple#45]
Traceback (most recent call last):
  File "D:\python\py\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\python\py\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\python\py\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python\py\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Beijing_Daxuexi_Simple-main\main.py", line 43, in <module>
    if study(username, password, ua):
  File "D:\python\Beijing_Daxuexi_Simple-main\study.py", line 62, in study
    haveLearned = bjySession.get(learnedInfo).json()
  File "D:\python\py\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

**Comment by rujiewu** [comment]
There are no "daxuexi" in this semester, and the returned json is empty, which leads to this error.

Run it at next semester.

**Comment by surreyskahn** [comment]
Thanks
