### ISSUE TITLE
Exception: 组织id不匹配

### ISSUE THREAD

**Issue by AtlandisLee** [startkkkkkk/Beijing_Daxuexi_Simple#52]
登录成功
获取组织id-2
无法获取orgID
Traceback (most recent call last):
  File "D:\ShareCache\Office-PKU\团支书工作\Beijing_Daxuexi_Simple-main\main.py", line 51, in <module>
    if study(username, password, ua):
  File "D:\ShareCache\Office-PKU\团支书工作\Beijing_Daxuexi_Simple-main\study.py", line 101, in study
    raise Exception('组织id不匹配，如果看到这个请开个issue说下')
Exception: 组织id不匹配，如果看到这个请开个issue说下

**Comment by AtlandisLee** [comment]
orgIdTemp = orgPattern.search(bjySession.get('https://m.bjyouth.net/dxx/my').json()['data']['org'])
是这个里面的网址不能用了吗

**Comment by qiuxiaohuo** [comment]
我第一次尝试也是相同的报错信息:  
```
账号数量：1
--User 1--
登录成功
获取组织id-2
无法获取orgID
Traceback (most recent call last):
  File "../Beijing_Daxuexi_Simple/main.py", line 66, in <module>
    if study(username, password, ua):
  File "../Beijing_Daxuexi_Simple/study.py", line 101, in study
    raise Exception('组织id不匹配，如果看到这个请开个issue说下')
Exception: 组织id不匹配，如果看到这个请开个issue说下
```  
我关闭我的 clash 代理, 重新运行程序, 得到如下信息:
```
账号数量：1
--User 1--
Login:识别的验证码错误
登录成功
青年大学习：xxx 在运行前已完成,退出
--Summary--
成功：1，失败：0
```
我检查了一下公众号上的学习记录, 是存在的, 所以应该是通过了
-----
我的运行平台是 **wsl Ubuntu 22.04**
