### ISSUE TITLE
等个更新

### ISSUE THREAD

**Issue by mayjack0312** [startkkkkkk/Beijing_Daxuexi_Simple#58]
--User 1--
Traceback (most recent call last):
  File "C:\Users\LMY\Desktop\Daxuexi\study.py", line 25, in study
    capText = cap_recognize(bjySession.get(url=capUrl).content)
  File "C:\Users\LMY\Desktop\Daxuexi\utility.py", line 27, in cap_recognize
    return DdddOcr().classification(denoise(cap))
  File "C:\Users\LMY\Desktop\Daxuexi\utility.py", line 31, in denoise
    img = Image.open(BytesIO(cap))
  File "c:\Users\LMY\Desktop\Daxuexi\venv38\lib\site-packages\PIL\Image.py", line 3280, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001F6FFEA5F40>

Traceback (most recent call last):
  File "C:\Users\LMY\Desktop\Daxuexi\study.py", line 21, in study
    capUrl = "https://m.bjyouth.net" + re.findall(
IndexError: list index out of range

Login:识别的验证码错误
Traceback (most recent call last):
  File "C:\Users\LMY\Desktop\Daxuexi\study.py", line 21, in study
    capUrl = "https://m.bjyouth.net" + re.findall(
IndexError: list index out of range

登录成功
Traceback (most recent call last):
  File "C:\Users\LMY\Desktop\Daxuexi\study.py", line 42, in study
    r = json.loads(bjySession.get("https://m.bjyouth.net/dxx/index").text)
  File "C:\Users\LMY\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\LMY\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\LMY\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

登入失败,退出

**Comment by mayjack0312** [comment]
--User 1--
Traceback (most recent call last):
  File "C:\Users\LMY\Desktop\Daxuexi\study.py", line 25, in study
    capText = cap_recognize(bjySession.get(url=capUrl).content)
  File "C:\Users\LMY\Desktop\Daxuexi\utility.py", line 27, in cap_recognize
    return DdddOcr().classification(denoise(cap))
  File "C:\Users\LMY\Desktop\Daxuexi\utility.py", line 31, in denoise
    img = Image.open(BytesIO(cap))
  File "c:\Users\LMY\Desktop\Daxuexi\venv38\lib\site-packages\PIL\Image.py", line 3280, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001F6FFEA5F40>

Traceback (most recent call last):
  File "C:\Users\LMY\Desktop\Daxuexi\study.py", line 21, in study
    capUrl = "https://m.bjyouth.net" + re.findall(
IndexError: list index out of range

Login:识别的验证码错误
Traceback (most recent call last):
  File "C:\Users\LMY\Desktop\Daxuexi\study.py", line 21, in study
    capUrl = "https://m.bjyouth.net" + re.findall(
IndexError: list index out of range

登录成功
Traceback (most recent call last):
  File "C:\Users\LMY\Desktop\Daxuexi\study.py", line 42, in study
    r = json.loads(bjySession.get("https://m.bjyouth.net/dxx/index").text)
  File "C:\Users\LMY\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\LMY\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\LMY\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

登入失败,退出
